# apps/worker/monitors.py
# Single source of truth for all monitored routes.
# Mirrors packages/shared/src/monitors.ts

CASH_MONITORS = [
    {
        "id": "yyc-yyz-jul2-window",
        "kind": "cash",
        "origin": "YYC",
        "destination": "YYZ",
        "date_from": "2026-06-28",
        "date_to": "2026-07-06",
        "trip_type": "one_way",
        "preferred_carriers": ["AC", "WS", "F8"],
    },
    {
        "id": "yyc-yyz-jul13-window",
        "kind": "cash",
        "origin": "YYC",
        "destination": "YYZ",
        "date_from": "2026-07-09",
        "date_to": "2026-07-17",
        "trip_type": "one_way",
        "preferred_carriers": ["AC", "WS", "F8"],
    },
    {
        "id": "yyc-yyz-jul14-window",
        "kind": "cash",
        "origin": "YYC",
        "destination": "YYZ",
        "date_from": "2026-07-10",
        "date_to": "2026-07-18",
        "trip_type": "one_way",
        "preferred_carriers": ["AC", "WS", "F8"],
    },
    {
        "id": "yyz-yyc-june-last-week",
        "kind": "cash",
        "origin": "YYZ",
        "destination": "YYC",
        "date_from": "2026-06-24",
        "date_to": "2026-06-30",
        "trip_type": "one_way",
        "preferred_carriers": ["AC", "WS", "F8"],
    },
    {
        "id": "yyz-yyc-may8-window",
        "kind": "cash",
        "origin": "YYZ",
        "destination": "YYC",
        "date_from": "2026-05-03",
        "date_to": "2026-05-13",
        "trip_type": "one_way",
        "preferred_carriers": ["AC", "WS", "F8"],
    },
    {
        "id": "yyz-yyc-june10",
        "kind": "cash",
        "origin": "YYZ",
        "destination": "YYC",
        "date_from": "2026-06-10",
        "date_to": "2026-06-10",
        "trip_type": "one_way",
        "preferred_carriers": ["AC", "WS", "F8"],
    },
    {
        "id": "yyc-yyz-june13",
        "kind": "cash",
        "origin": "YYC",
        "destination": "YYZ",
        "date_from": "2026-06-13",
        "date_to": "2026-06-13",
        "trip_type": "one_way",
        "preferred_carriers": ["AC", "WS", "F8"],
    },
]

AWARD_MONITORS = [
    # ── Islamabad ──────────────────────────────────────────────────────────
    {
        "id": "qatar-award-yyz-isb-jun2027",
        "kind": "award",
        "airline": "Qatar Airways",
        "origin": "YYZ",
        "destination": "ISB",
        "month": "2027-06",
        "cabin": "business",
    },
    {
        "id": "qatar-award-yyz-isb-jul2027",
        "kind": "award",
        "airline": "Qatar Airways",
        "origin": "YYZ",
        "destination": "ISB",
        "month": "2027-07",
        "cabin": "business",
    },
    {
        "id": "qatar-award-yyz-isb-dec2027",
        "kind": "award",
        "airline": "Qatar Airways",
        "origin": "YYZ",
        "destination": "ISB",
        "month": "2027-12",
        "cabin": "business",
    },
    # ── Istanbul IST ───────────────────────────────────────────────────────
    {
        "id": "qatar-award-yyz-ist-jun2027",
        "kind": "award",
        "airline": "Qatar Airways",
        "origin": "YYZ",
        "destination": "IST",
        "month": "2027-06",
        "cabin": "business",
    },
    {
        "id": "qatar-award-yyz-ist-jul2027",
        "kind": "award",
        "airline": "Qatar Airways",
        "origin": "YYZ",
        "destination": "IST",
        "month": "2027-07",
        "cabin": "business",
    },
    {
        "id": "qatar-award-yyz-ist-dec2027",
        "kind": "award",
        "airline": "Qatar Airways",
        "origin": "YYZ",
        "destination": "IST",
        "month": "2027-12",
        "cabin": "business",
    },
    # ── Istanbul SAW ───────────────────────────────────────────────────────
    {
        "id": "qatar-award-yyz-saw-jun2027",
        "kind": "award",
        "airline": "Qatar Airways",
        "origin": "YYZ",
        "destination": "SAW",
        "month": "2027-06",
        "cabin": "business",
    },
    {
        "id": "qatar-award-yyz-saw-jul2027",
        "kind": "award",
        "airline": "Qatar Airways",
        "origin": "YYZ",
        "destination": "SAW",
        "month": "2027-07",
        "cabin": "business",
    },
    {
        "id": "qatar-award-yyz-saw-dec2027",
        "kind": "award",
        "airline": "Qatar Airways",
        "origin": "YYZ",
        "destination": "SAW",
        "month": "2027-12",
        "cabin": "business",
    },
]

ALL_MONITORS = CASH_MONITORS + AWARD_MONITORS
