// packages/shared/src/monitors.ts
import { Monitor } from "./types";

export const monitors: Monitor[] = [
  // ─── Domestic Cash Monitors ───────────────────────────────────────────────

  {
    id: "yyc-yyz-jul2-window",
    kind: "cash",
    origin: "YYC",
    destination: "YYZ",
    dateFrom: "2026-06-28",
    dateTo: "2026-07-06",
    tripType: "one_way",
    preferredCarriers: ["AC", "WS", "F8"],
  },
  {
    id: "yyc-yyz-jul13-window",
    kind: "cash",
    origin: "YYC",
    destination: "YYZ",
    dateFrom: "2026-07-09",
    dateTo: "2026-07-17",
    tripType: "one_way",
    preferredCarriers: ["AC", "WS", "F8"],
  },
  {
    id: "yyc-yyz-jul14-window",
    kind: "cash",
    origin: "YYC",
    destination: "YYZ",
    dateFrom: "2026-07-10",
    dateTo: "2026-07-18",
    tripType: "one_way",
    preferredCarriers: ["AC", "WS", "F8"],
  },
  {
    id: "yyz-yyc-june-last-week",
    kind: "cash",
    origin: "YYZ",
    destination: "YYC",
    dateFrom: "2026-06-24",
    dateTo: "2026-06-30",
    tripType: "one_way",
    preferredCarriers: ["AC", "WS", "F8"],
  },
  {
    id: "yyz-yyc-may8-window",
    kind: "cash",
    origin: "YYZ",
    destination: "YYC",
    dateFrom: "2026-05-03",
    dateTo: "2026-05-13",
    tripType: "one_way",
    preferredCarriers: ["AC", "WS", "F8"],
  },
  {
    id: "yyz-yyc-june10",
    kind: "cash",
    origin: "YYZ",
    destination: "YYC",
    dateFrom: "2026-06-10",
    dateTo: "2026-06-10",
    tripType: "one_way",
    preferredCarriers: ["AC", "WS", "F8"],
  },
  {
    id: "yyc-yyz-june13",
    kind: "cash",
    origin: "YYC",
    destination: "YYZ",
    dateFrom: "2026-06-13",
    dateTo: "2026-06-13",
    tripType: "one_way",
    preferredCarriers: ["AC", "WS", "F8"],
  },

  // ─── Qatar Award Monitors – Islamabad ─────────────────────────────────────

  {
    id: "qatar-award-yyz-isb-jun2027",
    kind: "award",
    airline: "Qatar Airways",
    origin: "YYZ",
    destination: "ISB",
    month: "2027-06",
    cabin: "business",
  },
  {
    id: "qatar-award-yyz-isb-jul2027",
    kind: "award",
    airline: "Qatar Airways",
    origin: "YYZ",
    destination: "ISB",
    month: "2027-07",
    cabin: "business",
  },
  {
    id: "qatar-award-yyz-isb-dec2027",
    kind: "award",
    airline: "Qatar Airways",
    origin: "YYZ",
    destination: "ISB",
    month: "2027-12",
    cabin: "business",
  },

  // ─── Qatar Award Monitors – Istanbul IST ──────────────────────────────────

  {
    id: "qatar-award-yyz-ist-jun2027",
    kind: "award",
    airline: "Qatar Airways",
    origin: "YYZ",
    destination: "IST",
    month: "2027-06",
    cabin: "business",
  },
  {
    id: "qatar-award-yyz-ist-jul2027",
    kind: "award",
    airline: "Qatar Airways",
    origin: "YYZ",
    destination: "IST",
    month: "2027-07",
    cabin: "business",
  },
  {
    id: "qatar-award-yyz-ist-dec2027",
    kind: "award",
    airline: "Qatar Airways",
    origin: "YYZ",
    destination: "IST",
    month: "2027-12",
    cabin: "business",
  },

  // ─── Qatar Award Monitors – Istanbul SAW ──────────────────────────────────

  {
    id: "qatar-award-yyz-saw-jun2027",
    kind: "award",
    airline: "Qatar Airways",
    origin: "YYZ",
    destination: "SAW",
    month: "2027-06",
    cabin: "business",
  },
  {
    id: "qatar-award-yyz-saw-jul2027",
    kind: "award",
    airline: "Qatar Airways",
    origin: "YYZ",
    destination: "SAW",
    month: "2027-07",
    cabin: "business",
  },
  {
    id: "qatar-award-yyz-saw-dec2027",
    kind: "award",
    airline: "Qatar Airways",
    origin: "YYZ",
    destination: "SAW",
    month: "2027-12",
    cabin: "business",
  },
];
